# Generated by Django 2.0.2 on 2018-03-10 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_auto_20180310_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOfContentsNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_root', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='parent',
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AddField(
            model_name='tableofcontentsnode',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Article'),
        ),
        migrations.AddField(
            model_name='tableofcontentsnode',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='guide.TableOfContentsNode'),
        ),
    ]
