# Generated by Django 2.0.2 on 2018-03-10 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_auto_20180310_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableofcontentsnode',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toc_node', to='guide.Article'),
        ),
    ]
