# Generated by Django 2.0.2 on 2018-03-10 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_auto_20180310_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableofcontentsnode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='guide.TableOfContentsNode'),
        ),
    ]
